image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/replicator
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi
replicas: 1
apiserverIP: "" # mapping value from Fasit
debug: false
