---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-replicatorconfig
  failurePolicy: Fail
  name: replicatorconfiguration.nais.io
  rules:
  - apiGroups:
    - nais.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicatorconfigurations
  sideEffects: None
