apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "replicator.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "replicator.labels" . | nindent 4 }}
spec:
  selfSigned: {}