{{ if .Values.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "replicator.fullname" . }}-controller-manager-metrics-monitor
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: replicator
    app.kubernetes.io/part-of: replicator
    control-plane: controller-manager
  {{- include "replicator.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: replicator
      control-plane: controller-manager
{{ end }}
