# permissions for end users to view replicationconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: replicationconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: replicator
    app.kubernetes.io/part-of: replicator
    app.kubernetes.io/managed-by: kustomize
  name: replicationconfig-viewer-role
rules:
- apiGroups:
  - nais.io
  resources:
  - replicationconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nais.io
  resources:
  - replicationconfigs/status
  verbs:
  - get
