apiVersion: nais.io/v1
kind: ReplicationConfig
metadata:
  name: team-resources
spec:
  namespaceSelector:
    #matchLabels:
    #  team-namespace: "true"
    matchExpressions:
      - key: team
        operator: Exists
  templateValues:
    values:
      project: abc-123
#    secrets:
#      - name: secret-containing-value
    namespace:
      labels:
        - team
      annotations:
        - beam

  resources:
    - template: |
        kind: Secret
        apiVersion: v1
        type: kubernetes.io/Opaque
        metadata:
          name: replicator-secret
        stringData:
          apiKey: [[ .Values.team ]] # loaded from secret 
