apiVersion: nais.io/v1
kind: ReplicationConfig
metadata:
  name: create-secrets
spec:
  namespaceSelector:
    matchLabels:
      team-namespace: "true"
  values:
    secrets:
      - name: secret-to-load
        namespace: replicator-system
#      - namespace #if empty it will use the namespace of the replicatorconfig
    configMaps:
      - name: configmap-to-load
        namespace: replicator-system
  resources:
    - template: | 
        apiVersion: v1
        kind: Secret
        type: kubernetes.io/Opaque
        metadata:
          name: replicator-secret-1
        stringData: 
          fromSecret: [[ .Values.s1 ]]
          fromConfigMap: [[ .Values.cm1 ]]
          fromNs: [[ .Values.ns_value ]]
