apiVersion: nais.io/v1
kind: ReplicationConfig
metadata:
  name: create-secrets
spec:
  namespaceSelector:
    matchLabels:
      team-namespace: "true"
  valueSecrets:
    - name: secret-to-load
  resources:
    - template: |
        apiVersion: v1
        kind: Secret
        type: kubernetes.io/Opaque
        metadata:
          name: replicator-secret-1
        stringData: 
          fromSecret: [[ .Values.s1 ]]
          fromNs: [[ .Values.ns_value ]]
