apiVersion: nais.io/v1
kind: ReplicatorConfiguration
metadata:
  name: alerting2
spec:
  namespaceSelector:
    matchLabels:
      team-namespace: "true"
#    values:
#      secrets:
#        - name: slack-webhook # loads data from secret (data: foo: bar)
#  values:
#    secret:
#      - name: slack-webhook # loads data from secret (data: foo: bar)
  resources:
    - template: | 
        apiVersion: v1
        kind: Secret
        type: kubernetes.io/Opaque
        metadata:
          name: slack-webhook
        stringData: 
          apiKey: {{ .Values.foo }} # loaded from secret
    - template: | 
        kind: AlertmanagerConfig
        apiVersion: monitoring.coreos.com
        metadata:
          name: yolo-alerts
        data:
          receivers:
            - name: yolo
              slackConfigs:
                - apiURL:
                    key: apiUrl
                    name: slack-webhook
                  sendResolved: true
          route:
            receiver: yolo
            groupBy:
              - alertname
            groupInterval: 5m
            groupWait: 10s
            repeatInterval: 1h    
