apiVersion: nais.io/v1
kind: ReplicatorConfiguration
metadata:
  name: alerting
spec:
  namespaceSelector:
    matchLabels:
      team-namespace: "true"
  resources:
    - template: | 
        apiVersion: v1
        kind: Secret
        type: kubernetes.io/Opaque
        metadata:
          name: slack-webhook
        stringData: 
            apiKey: {{ .Values.tommy }} # loaded from secret
