apiVersion: nais.io/v1
kind: ReplicatorConfiguration
metadata:
  name: alerting
spec:
  namespaceSelector:
    matchLabels:
      team-namespace: "true"
    values:
      secrets:
        - name: slack-webhook # loads data from secret (data: foo: bar)
#  values:
#    secret:
#      - name: slack-webhook # loads data from secret (data: foo: bar)
  resources:
    - template: | 
        apiVersion: v1
        type: kubernetes.io/Opaque
        metadata:
          name: slack-webhook
        data:
          stringData: 
             apiKey: {{ .Values.slack-webhook }} # loaded from secret