apiVersion: v1
kind: Namespace
metadata:
  annotations:
    replicator.nais.io/ns_value: "foo"
  labels:
    team-namespace: "true"
  name: replicator-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: replicator-system
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-to-load
  namespace: replicator-system
type: kubernetes.io/Opaque
stringData:
  s1: s1fromsecret
