dependencies:
  - allOf:
    - cert-manager
environmentKinds:
  - tenant
  - onprem
  - management
values:
  apiserverIP:
    displayName: API server IP
    computed:
      template: '"{{ .Env.apiserver_endpoint }}"'
  debug:
    description: Enable debug logging
    displayName: Debug
    config:
      type: bool

