apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "replicator.fullname" . }}-serving-cert
  labels:
  {{- include "replicator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "replicator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "replicator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: '{{ include "replicator.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert