apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "replicator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "replicator.fullname" . }}-serving-cert
  labels:
  {{- include "replicator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "replicator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-replicationconfig
  failurePolicy: Fail
  name: replicationconfiguration.nais.io
  rules:
  - apiGroups:
    - nais.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicationconfigurations
  sideEffects: None