apiVersion: v1
kind: Service
metadata:
  name: {{ include "replicator.fullname" . }}-webhook-service
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: replicator
    app.kubernetes.io/part-of: replicator
  {{- include "replicator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
  {{- include "replicator.selectorLabels" . | nindent 4 }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443