image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/replicator
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
replicas: 1
apiserverIP: "" # mapping value from Fasit